# ./docker-compose.dev.yml

version: '3'

services:
  webapp:
    env_file:
       - docker/env/prod.conf
    volumes:
       - "./:/var/www"
       - "/etc/letsencrypt/live/ouxsoft.com/:/etc/apache2/certs"