#
# Component Config
#
version: 1
elements:
  # skip processing element with ancestor set to false by using:
  # xpath: "//element[not(ancestor::*[@process='false'])]"
  types:
    - name: 'Code'
      xpath: "//code[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\Code'

    - name: 'If Statement'
      xpath: "//if[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\IfStatement'

    - name: 'Variable'
      xpath: "//var[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\Variable'

#    - name: 'Image'
#      xpath: "//img[not(ancestor::*[@process='false'])]"
#      class_name: 'LHTML\Element\Core\Image'

    - name: 'Hyperlink'
      xpath: "//a[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\Hyperlink'

    - name: 'Redact'
      xpath: "//redact[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\Redact'

    - name: "Block[not(ancestor::*[@process='false'])]"
      xpath: "//block[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Blocks\{name}'

    - name: 'Partial'
      xpath: "//partial[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Partial\{name}'

    - name: 'Widget'
      xpath: "//widget[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Widgets\{name}'
      settings:
        - cache_duration: '1 hour'
        - search_index: false

      # Do not process nav under main, such as tabs
    - name: "Nav"
      xpath: "//nav[not(ancestor::*[@process='false']|ancestor::main)]"
      class_name: 'LHTML\Element\Custom\Nav\{name}'

    - name: "Head"
      xpath: "//head[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Head\{name}'

    - name: "Header"
      xpath: "//header[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Header\{name}'

    - name: "Main"
      xpath: "//main[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Main\{name}'

    - name: "Alert"
      xpath: "//alert[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Partial\Alert'

    - name: "Footer"
      xpath: "//footer[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Footer\{name}'

    - name: 'Example'
      xpath: "//example[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Example\{name}'

  # auto call these methods
  methods:
    - name: 'beforeLoad'
      descirption: 'Execute before object data load'

    - name: 'onLoad'
      descirption: 'Execute during object data load'

    - name: 'afterLoad'
      description: 'Execute after object data loaded'

    - name: 'beforeRender'
      description: 'Execute before object render'

    - name: 'onRender'
      description: 'Execute during object render'
      execute: 'RETURN_CALL'

    - name: 'afterRender'
      descirption: 'Execute after object rendered'