#
# Component Config
#
version: 1
elements:
  # skip processing element with ancestor set to false by using:
  # xpath: "//element[not(ancestor::*[@process='false'])]"
  types:
    - name: 'Code'
      xpath: "//code[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\Code'
    - name: 'If Statement'
      xpath: "//if[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\IfStatement'
    - name: 'Variable'
      xpath: "//var[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\Variable'
#    - name: 'Image'
#      xpath: "//img[not(ancestor::*[@process='false'])]"
#      class_name: 'LHTML\Element\Core\Image'
    - name: 'Hyperlink'
      xpath: "//a[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\Hyperlink'
    - name: 'Redact'
      xpath: "//redact[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Core\Redact'
    - name: "Block[not(ancestor::*[@process='false'])]"
      class_name: 'LHTML\Element\Custom\Blocks\{name}'
      xpath: "//block[not(ancestor::*[@process='false'])]"
      settings:
        - cache_duration: '1 hour'
        - search_index: false
    - name: 'Partial'
      class_name: 'LHTML\Element\Custom\Partials\{name}'
      xpath: "//partial[not(ancestor::*[@process='false'])]"
    - name: 'Widget'
      class_name: 'LHTML\Element\Custom\Widgets\{name}'
      xpath: "//widget[not(ancestor::*[@process='false'])]"
    - name: "Nav"
      class_name: 'LHTML\Element\Custom\Nav\{name}'
      xpath: "//nav[not(ancestor::*[@process='false']|ancestor::main)]" # Do not process nav under main, such as tabs
    - name: "Head"
      class_name: 'LHTML\Element\Custom\Head\{name}'
      xpath: "//head[not(ancestor::*[@process='false'])]"
    - name: "Header"
      class_name: 'LHTML\Element\Custom\Header\{name}'
      xpath: "//header[not(ancestor::*[@process='false'])]"
    - name: "Main"
      class_name: 'LHTML\Element\Custom\MainContent\{name}'
      xpath: "//main[not(ancestor::*[@process='false'])]"
    - name: "Footer"
      class_name: 'LHTML\Element\Custom\Footer\{name}'
      xpath: "//footer[not(ancestor::*[@process='false'])]"
    - name: 'Example'
      class_name: 'LHTML\Element\Custom\Examples\{name}'
      xpath: "//example[not(ancestor::*[@process='false'])]"
  # auto call these methods
  methods:
    - name: 'beforeLoad'
      descirption: 'Execute before object data load'
    - name: 'onLoad'
      descirption: 'Execute during object data load'
    - name: 'afterLoad'
      description: 'Execute after object data loaded'
    - name: 'beforeRender'
      description: 'Execute before object render'
    - name: 'onRender'
      description: 'Execute during object render'
      execute: 'RETURN_CALL'
    - name: 'afterRender'
      descirption: 'Execute after object rendered'